version: '3'

services:
    start:
        image: node:14
        command: sh -c "npm start"
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 3000:3000

    install:
        image: node:14
        command: sh -c "yarn install"
        working_dir: /app
        volumes:
            - ./:/app

    build:
        image: node:14
        command: sh -c "yarn build"
        working_dir: /app
        volumes:
            - ./:/app
    S3:
       image: amazon/aws-cli:latest
       tty: true
       command:  s3 sync /app/build/ s3://horse.behodler.io
       volumes:
        - ./:/app
        - ~/.aws:/root/.aws